### ISSUE TITLE
Working on local samples

### ISSUE THREAD

**Issue by mr-eyes** [pirovc/grimer#1]
Hi,
Thanks for this awesome tool!

I am studying some samples that might contain microbial and non-microbial eukaryotes. Samples are RNAseq PE and saved locally. Is there a way to run this pipeline to generate such a beautiful report?

Thanks,
—Mo

**Comment by pirovc** [comment]
Hi! You're welcome. GRIMER just provides the visualization step, so you have to come with a table of counts (samples x observations) generated with your method of choice. Once you are there feel free to ask for further assistance.

**Comment by mr-eyes** [comment]
Got it! Thanks for the quick reply.
