### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by RichStack** [pirovc/grimer#6]
Hi, I'm wondering if you can help me.
I am trying to install grimer as a conda environment on my local university cluster using mamba.
Initially I had a problem with the version of R, so created an environment first with the required R=4.0
However, I am still getting this message:
`The following package could not be installed
└─ grimer   is uninstallable because it requires
   └─ biom-format >=2.1.10 , which conflicts with any installable versions previously reported.`
I'm not sure how to resolve this issue, as I have biom-format installed, and all dependencies such as h5py are installed and up to date.

It is perfectly possible that I am doing something stupid or missing an important step.
Looking forward to trying this tool out, and would be grateful for any pointers on how to resolve this issue.

Kind regards,
Richard

**Comment by pirovc** [comment]
Not sure how you are trying to install it but I'd suggest to create a different environment to avoid dependency issues, for example: `mamba create -n grimer grimer` and then `source activate grimer` to enter the env. and use the tool.

**Comment by RichStack** [comment]
Thanks very much for taking the time to answer and solve a newbie question. Everything worked great.
